name: Checks
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      -
        name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      -
        name: Check formatting
        run: vendor/bin/ecs

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3']
        dependency-version: [ prefer-lowest, prefer-stable ]
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      -
        name: Install dependencies
        run: composer update --no-progress --${{ matrix.dependency-version }} --prefer-dist --no-interaction
      -
        name: Run PHPUnit tests
        run: composer test